### ISSUE TITLE
Error loading: ImportError: cannot import name 'TCDScheduler' from 'diffusers' 

### ISSUE THREAD

**Issue by Maelstrom2014** [smthemex/ComfyUI_Stable_Makeup#12]
Error loading: ImportError: cannot import name 'TCDScheduler' from 'diffusers' 

LOADING LOG:
Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\__init__.py", line 2, in <module>
    from .stable_makeup_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\stable_makeup_nodes.py", line 8, in <module>
    from diffusers import (DDIMScheduler, ControlNetModel,
ImportError: cannot import name 'TCDScheduler' from 'diffusers' (C:\ai\comfyui\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup module for custom nodes: cannot import name 'TCDScheduler' from 'diffusers' (C:\ai\comfyui\python_embeded\Lib\site-packages\diffusers\__init__.py)
Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 27, in <module>
    from diffusers import (StableDiffusionXLPipeline, DiffusionPipeline, DDIMScheduler, ControlNetModel,
ImportError: cannot import name 'TCDScheduler' from 'diffusers' (C:\ai\comfyui\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: cannot import name 'TCDScheduler' from 'diffusers' (C:\ai\comfyui\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by Maelstrom2014** [comment]
SOLUTION:
.\python_embeded\python.exe -m pip install -U diffusers==0.27.2
