### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/'

### ISSUE THREAD

**Issue by RGX650** [smthemex/ComfyUI_Stable_Makeup#5]
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\nodes.py", line 1930, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\__init__.py", line 2, in <module>
    from .stable_makeup_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\stable_makeup_nodes.py", line 32, in <module>
    detector = FaceDetector(weight_path=os.path.join(weigths_current_path,"mobilenet0.25_Final.pth"))
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\facelib\Retinaface\Retinaface.py", line 36, in __init__
    os.makedirs(os.path.split(weight_path)[0], exist_ok=True)
  File "C:\Program Files\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/'

**Comment by smthemex** [comment]
Known bug, I fixed it today
